apiVersion: v2
name: mc-operator
description: A Kubernetes Operator for managing Minecraft server deployments — powered by .NET 10 and KubeOps.
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - minecraft
  - operator
  - kubernetes
  - gaming
home: https://hengeveld.dev/mc-operator
sources:
  - https://github.com/danihengeveld/mc-operator
maintainers:
  - name: danihengeveld
    email: dani@hengeveld.dev
    url: https://hengeveld.dev
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: ""
    url: ""
