apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mc-operator-role
rules:
- apiGroups:
  - apps
  nonResourceURLs: []
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  nonResourceURLs: []
  resources:
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - ""
  nonResourceURLs: []
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  nonResourceURLs: []
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - batch
  nonResourceURLs: []
  resources:
  - jobs
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - coordination.k8s.io
  nonResourceURLs: []
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - mc-operator.dhv.sh
  resources:
  - minecraftservers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mc-operator.dhv.sh
  resources:
  - minecraftservers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - mc-operator.dhv.sh
  resources:
  - minecraftserverclusters
  verbs:
  - '*'
- apiGroups:
  - mc-operator.dhv.sh
  resources:
  - minecraftserverclusters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'